chore: add step - verify secret present

diff --git a/.github/workflows/publish-package.yml b/.github/workflows/publish-package.yml
--- a/.github/workflows/publish-package.yml
+++ b/.github/workflows/publish-package.yml
@@ -16,6 +16,17 @@ jobs:
         with:
           python-version: "3.13"
 
+      - name: Verify secrets
+        env:
+          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
+        run: |
+          if [ -z "$TWINE_PASSWORD" ]; then
+            echo "Secrets missing ❌"
+            exit 1
+          else
+            echo "Secrets present ✔"
+          fi
+
       - name: Install build tools
         run: |
           python -m pip install --upgrade pip
